# Generated by Django 2.1.5 on 2019-01-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=25)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('current_company', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(max_length=50)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_list', to='myapp.Experience')),
            ],
        ),
    ]
