# Generated by Django 2.1.5 on 2019-01-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='skillset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_list', to='myapp.Skillset'),
        ),
    ]
