# Generated by Django 2.1.5 on 2019-01-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190128_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('recommendation', models.CharField(max_length=500)),
            ],
        ),
    ]
