# Generated by Django 2.1.5 on 2019-02-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact_home_homeimage_paragraph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
