# Generated by Django 2.1.5 on 2019-02-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibility',
            name='exp',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Responsibility',
        ),
    ]
