# Generated by Django 2.1.5 on 2019-02-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190201_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('current_company', models.BooleanField()),
                ('role', models.CharField(max_length=25)),
                ('current_role', models.BooleanField()),
                ('from_date', models.DateField(verbose_name='validators=[validate_date]')),
                ('to_date', models.DateField(verbose_name='validators=[validate_date]')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(max_length=50)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_list', to='myapp.Experience')),
            ],
        ),
        migrations.AddField(
            model_name='awards',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_list', to='myapp.Experience'),
        ),
    ]
